apiVersion: 1

contactPoints:
  - orgId: 1
    name: ntfy
    receivers:
      - uid: ntfy
        type: webhook
        settings:
          url: http://ntfy/alerts
          httpMethod: POST
          maxRetries: 3
          body: |
            {{ range .Alerts }}
            ğŸš¨ Alert: {{ .Labels.alertname }}
            ğŸ“ Instance: {{ .Labels.instance }}
            âš ï¸ Severity: {{ .Labels.severity }}
            ğŸ“ Description: {{ .Annotations.description }}
            ğŸ•’ Starts At: {{ .StartsAt }}
            {{ end }}
