---
- name: Install UFW
  apt:
    name: ufw
    state: present
  when: enable_ufw

- name: Set default deny incoming
  ufw:
    state: enabled
    direction: in
    policy: deny
  when: enable_ufw

- name: Set default allow outgoing
  ufw:
    direction: out
    policy: allow
  when: enable_ufw

- name: Allow SSH
  ufw:
    rule: allow
    name: OpenSSH
  when: enable_ufw
